publish:
  image: clickable/ci-16.04-armhf
  only:
    - tags
  script:
    - dd if=/dev/zero of=/swapfile count=4096 bs=1MiB
    - chmod 600 /swapfile
    - mkswap /swapfile
    - swapon /swapfile
    - swapon --show
    - clickable clean build click-build
    - clickable publish "$CI_COMMIT_MESSAGE"
  artifacts:
    paths:
      - build/*.click
    expire_in: 1 week

build:
  image: clickable/ci-16.04-armhf
  except:
    - tags
  script:
    - dd if=/dev/zero of=/swapfile count=4096 bs=1MiB
    - chmod 600 /swapfile
    - mkswap /swapfile
    - swapon /swapfile
    - swapon --show
    - clickable clean build click-build
  artifacts:
    paths:
      - build/*.click
    expire_in: 1 week
