publish:
  image: clickable/ci-16.04-armhf
  script:
    - cd prebuilt
    - clickable clean build
    - cd build
    - ls -Ral
    - mv armhf all
    - cd all/app
    - rename 's/armhf/all/' *.click
    - cd ../../..
    - ls -Ral
    - clickable publish "$CI_COMMIT_MESSAGE"
  artifacts:
    paths:
      - prebuilt/build/all/app/*.click
    expire_in: 1 week

build:
  image: clickable/ci-16.04-armhf
  except:
    - tags
  script:
    - cd prebuilt
    - clickable clean build
  artifacts:
    paths:
      - prebuilt/build/all/app/*.click
    expire_in: 1 week
