publish:
  image: clickable/ci-16.04-armhf
  before_script:
    - mkdir build
    - cp -R src/app/qml prebuilt/qml
  script:
    - cd prebuilt
    - clickable clean build click-build
    - clickable publish "$CI_COMMIT_MESSAGE"
    - cp build/*.click ../build
  artifacts:
    paths:
      - build/*.click
    expire_in: 1 week

build:
  image: clickable/ci-16.04-armhf
  except:
    - tags
  before_script:
    - cp -R src/app/qml prebuilt/qml
  script:
    - cd prebuilt
    - clickable clean build click-build
  artifacts:
    paths:
      - prebuilt/build/*.click
    expire_in: 1 week
