publish:
  image: clickable/ci-16.04-armhf
  only:
    - tags
  before_script:
    - mkdir build
  script:
    - cd prebuilt
    - clickable clean build
    - cd build
    - rename 's/armhf/all/' *.click
    - cd ..
    - clickable publish "$CI_COMMIT_MESSAGE"
  artifacts:
    paths:
      - prebuilt/build/arm-linux-gnueabihf/app/*.click
    expire_in: 1 week

build:
  image: clickable/ci-16.04-armhf
  except:
    - tags
  script:
    - cd prebuilt
    - clickable clean build
  artifacts:
    paths:
      - build/arm-linux-gnueabihf/app/*.click
    expire_in: 1 week
