name: ubuntu-filemanager-app
version: 0.4
summary: File Manager application
description: Core File Manager application
confinement: devmode  # use "strict" to enforce system access only via declared interfaces
grade: devel

apps:
    ubuntu-filemanager-app:
        command: desktop-launch $SNAP/bin/ubuntu-filemanager-app "$@"
        plugs: [unity7, unity8, opengl, home, platform, mir]

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target: ubuntu-app-platform
        default-provider: ubuntu-app-platform

parts:
    ubuntu-filemanager-app:
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
        source: .
        build-packages:
            - cmake
            - gcc
            - g++
            - intltool
            - qtbase5-dev
            - qtdeclarative5-dev
            - qt5-default
            - pkg-kde-tools
            - python3-all
            - libtag1-dev
            - libpam0g-dev
            - libsmbclient-dev

        stage-packages:
            - libsmbclient           

        snap:
            - -usr/lib/python3
            - -usr/share/doc
            - -usr/include

        after: [desktop-ubuntu-app-platform]

    environment:
        source: snap/
        plugin: dump
        organize:
            ubuntu-filemanager-app.wrapper: bin/ubuntu-filemanager-app

